const schemeData =  {
    artBusiness:[{
        img:"/static/img/scheme/art-3d.png",
        name:"场景视觉化：3D展示场景",
        desc:"利用场景重建再设计技术实现场景数字化，满足当今用户/消费者的数字化期望",
        arrow:"体验3D艺术展馆的精彩",
        link:"https://obs.3dyunzhan.com/sceneFront/index.html?G_TEMP_ID=71ba61a3-2cdc-4129-676e-93d579eddedc"
    },
    {
        img:"/static/img/scheme/art-num.png",
        name:"展品数字化：文物/艺术品复刻",
        desc:"还原文物、艺术品的细节，最大限度保护和存储展品对人类文明的重大意义",
        arrow:"体验3D文物的细节",
        link:"https://www.51jianmo.com/#/modelDetails?modelCode=M0000062251000034CWH3&beforePage=%2FmodelSea"
    },
    {
        img:"/static/img/scheme/art-mange.png",
        name:"运营数字化：预测用户期望",
        desc:"数字化运营让场景的活动、展品的管理，用户的浏览习惯更直观体现，从而根据这些数据制定不同的服务",
        arrow:"感受精准的数字化运营",
    }
    ],
    goods:[
        {
            img:"/static/img/scheme/goods-dianpu.png",
            name:"店铺场景化：24h虚拟店铺",
            desc:"可根据节日、场景灵活调整3D虚拟店铺，让消费者可以感受新奇的购物体验",
            arrow:"体验3D虚拟店铺的奇妙",
            link:"http://www.3dyunzhan.com/scene-portal/b7b5e3d1-f344-4977-0ad7-b0e642e9c703.html"
        },
        {
            img:"/static/img/scheme/digit.png",
            name:"商品数字化：预测消费者期望",
            desc:"商品数字化让店铺的活动、商品的细节得以无死角的呈现，具备独特的营销推广能力，提高转化率从而获得更多的营销数据",
            arrow:"体会商品全角度的细节",
            link:"https://www.51jianmo.com/#/modelDetails?modelCode=M00000000810000358DTO&beforePage=%2FmodelSea"
        }
    ],
    house:[
        {
            img:"/static/img/scheme/house-fuke.png",
            name:"沙盘情境化：复刻与还原",
            desc:"将人们最感兴趣的楼盘布局、景观环境、配套设施以复刻或虚拟还原技术实现沙盘情境化",
            arrow:"浏览海景别墅",
            link:"http://www.3dyunzhan.com/scene-portal/25481870-ea6f-d11e-51d6-cefbbaa48a2f.html"
        },
        {
            img:"/static/img/scheme/house-num.png",
            name:"空间陈列：精装搭配先知",
            desc:"通过在线3D设计技术将户型/硬装结构、材料选择、软装搭配，智能完成多套精装方案",
            arrow:"了解在线空间设计",
            link:"http://jiaeda.com/tool"
        },
        {
            img:"/static/img/scheme/house-space.png",
            name:"运营数字化：数字售楼中心",
            desc:"数字售楼中心能将楼盘销售情况、客户管理、住户未来生活社区紧密结合一起，获得企业的私域流",
            arrow:"了解数字售楼中心",
        }
    ],
    science:[
        {
            img:"/static/img/scheme/science-history.png",
            name:"历史事件：3D场景重现",
            desc:"利用场景重建再设计技术实现场景数字化，让主题、历史事件更真实的还原于游览者眼前",
            arrow:"重游那段时刻",
        },
        {
            img:"/static/img/scheme/science-art.png",
            name:"革命文物：3D数字档案",
            desc:"三维扫描技术能将硬币大小的物件，高质量复刻并保存到展馆的数字档案区",
            arrow:"袁世凯大银元",
            link:"https://www.51jianmo.com/#/modelDetails?nextTradeType=&tradeType=&modelCode=M0000000001010137PLCO&beforePage=%2FmodelSea"
        },
        {
            img:"/static/img/scheme/science-guan.png",
            name:"展览教育：科学技术馆",
            desc:"以教育形式为展览教育，通过科学性、知识性、趣味性相结合3D展览内容和参与互动的形式，不仅普及科学知识，而且注重培养观众的科学思想、科学方法和科学精神。",
            arrow:"即将上线，敬请期待...",
        }
    ],
    enterprise:[
         {
            img:"/static/img/scheme/enterprise-3d.png",
            name:"企业形象化：3D形象建设",
            desc:"3D企业形象是一张无线传播的企业名片，承载着企业的使命、规模、服务，让企业的形象展示更直观",
            arrow:"参观名企的办公场所",
            link:"https://obs.3dyunzhan.com/sceneFront/index.html?G_TEMP_ID=acc12708-8398-29bc-ebf8-cf88378205c5"
        },
        {
            img:"/static/img/scheme/enterprise-num.png",
            name:"产品数字化：产品结构一览无遗",
            desc:"通过3D技术将产品的内外结构，小到螺丝钉都能全方位拆解",
            arrow:"拆解产品更多的细节",
            link:"https://www.51jianmo.com/#/indexPc?t=1566877082220.6208"
        },
        {
            img:"/static/img/scheme/enterprise-yunying.png",
            name:"运营数字化：市场跟踪与管理",
            desc:"可根据市场营销传播的企业名片获得潜在用户信息，并通过数据分析管理跟进业务进展等",
            arrow:"了解数字内部管理",
        }
    ],
    cooperation:[
       {
            img:"/static/img/scheme/enterprise1.png",
            name:"阿里巴巴(1688.com)",
            sub:"全球B2B电子商务著名品牌",
            desc:"2019年6月，第二届阿里巴巴跨境电商峰会在深圳举行。积木易搭为阿里巴巴提供电商数字化整体营销解决方案，通过3D商品建模以及3D数字展厅等手段，将商品与场景相结合，让3D赋能提升企业竞争优势。",
            link:"//1688.jimuyida.com/"
        },
        {
            img:"/static/img/scheme/enterprise2.png",
            name:"华侨城集团",
            sub:"大型国有中央企业",
            desc:"2018年10月，积木易搭与华侨城集团共同推出安仁华公馆3D光影数字展，作为全国首个线上与线下相结合的3D数字展览，一经推出就获得大量关注，为安仁古镇博物馆产业链数字化转型提供解决方案。"
        },
        {
            img:"/static/img/scheme/enterprise3.png",
            name:"平安科技",
            sub:"平安集团旗下科技解决方案专家",
            desc:"积木易搭与平安科技人工智能中心AI绘画团队共同推出平安慧画3D数字展厅，展示人工智能在画作自动生成和风格转换功能上取得的优秀成果。",
            link:"//pingan.jimuyida.com/"
        },
        {
            img:"/static/img/scheme/enterprise4.png",
            name:"海淀博物馆",
            sub:"地志性综合博物馆",
            desc:"积木易搭为海淀区博物提供文物3D扫描建模服务，文物数字化不仅丰富了海淀博物馆现有展览方式，也使观众能够通过更直观的方式了解文物更多的细节与文化知识，增进了观众的用户游览体验和获取知识的兴趣。"
        },
        {
            img:"/static/img/scheme/enterprise5.png",
            name:"全友家居",
            sub:"中国家具行业领军品牌",
            desc:"全友家私有限公司是一家集研、产、销一体的大型现代化家居企业。积木易搭与全友家私合作，为其提供线上3D样板间，将家居产品零售与场景相结合，提升购物体验，打造家居行业新零售样板案例。"
        },
        {
            img:"/static/img/scheme/enterprise6.png",
            name:"名家居世博园",
            sub:"世界级家居行业展示中心",
            desc:"积木易搭与名家居世博园联合打造“3D数字家居展馆”，为名家居世博园旗下500家国内外一线知名品牌厂商建立3D数字展厅，打造线上3D场景化体验，使用户足不出户便可畅游名家居世博园。",
            link:"//3dzt.jimuyida.com/static/webhome.html"
        }
    ]
}

//固话配置数据提高性能
export default Object.freeze(schemeData);
